before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - curl -sSL https://get.rvm.io | bash -s stable
  - source ~/.rvm/scripts/rvm
  - rvm install 2.3.1
  - rvm use 2.3.1 --default
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec rake db:setup RAILS_ENV=test

cucumber:
  script:
    - bundle exec cucumber
