default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gestao_development

test:
  <<: *default
  database: gestao_test

production:
  <<: *default
  database: gestao_production
  username: <%= ENV['GESTAO_DATABASE_USERNAME'] %>
  password: <%= ENV['GESTAO_DATABASE_PASSWORD'] %>
